version: "3.7"

services:
   nhanhoa232:
      image: proxy232:latest
      deploy:
         replicas: 1
         restart_policy:
            condition: any
      ports:
         - target: 80
           published: 80
           mode: host
         - target: 443
           published: 443
           mode: host
